name = "rompatcher-dx"
version = "0.1.0"
srcDir = "src"
defaultTargets = ["RompatcherDX", "rompatcher-dx"]

[[require]]
name = "Cli"
git = "https://github.com/leanprover/lean4-cli"
rev = "v4.30.0"

[[lean_lib]]
name = "RompatcherDX"

[[lean_exe]]
name = "rompatcher-dx"
root = "Main"
